futures_market/market/urls.py
"""
    Maps urls to views in market.views.
"""
from django.conf.urls.defaults import *

urlpatterns = patterns('market.views',
    (r'^$', 'index'),
    (r'^cancel/$', 'cancel_order'),
    (r'^upload/$', 'upload_data'),
    (r'^update/(?P<market_slug>[-\w]+)/$', 'update_market_info'),
    (r'^export/(?P<market_slug>[-\w]+)/$', 'export_data'),
    (r'^prices/(?P<market_slug>[-\w]+)/$', 'latest_prices'),
    (r'^orders/(?P<market_slug>[-\w]+)/$', 'get_orders'),
    (r'^portfolio/(?P<market_slug>[-\w]+)/(?P<trader_name>[-\w]+)/$', 'update_portfolio'),
    (r'^(?P<market_slug>[-\w]+)/$', 'market'),
    (r'^(?P<market_slug>[-\w]+)/(?P<trader_name>[-\w]+)/$', 'trader'),
)

futures_market/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
import re

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    # loads urls from market.urls
    (r'', include('market.urls')),
)

# Prefix all the above patterns with URL_PREFIX
# Note: All urls must begin with ^, and URL_PATTERN must begin with /
try:
    if settings.URL_PREFIX:
        prefixed_urlpattern = []
        for pat in urlpatterns:
            pat.regex = re.compile(r"^%s/%s" % (settings.URL_PREFIX[1:], pat.regex.pattern[1:]))
            prefixed_urlpattern.append(pat)
        urlpatterns = prefixed_urlpattern
except AttributeError as e:
    pass

futures_market/market/models/holding.py
from django.db import models
from market import Market
from stock import Stock
from trader import Trader

class Holding(models.Model):
    """Represents a holding in the market. Must be unique for the combination
       of (market, stock, trader)."""
    market = models.ForeignKey(Market)
    stock = models.ForeignKey(Stock)
    trader = models.ForeignKey(Trader)
    
    shares = models.IntegerField()

    class Meta:
        unique_together = ('market', 'stock', 'trader')
        app_label = 'market'

    def __unicode__(self):
        output = unicode(self.trader) + ': ' + unicode(self.stock) + ' ' + unicode(self.shares)
        return output

futures_market/market/models/market.py
from django.db import models
from datetime import datetime

class Market(models.Model):
    question = models.CharField(max_length=500, unique=True)
    slug = models.CharField(max_length=100, unique=True)
    creation_date = models.DateTimeField('date created',default=datetime.now())
    cash_endowment = models.DecimalField(max_digits=8, decimal_places=2) # initial cash endowment for users
    market_open = models.BooleanField()
    
    class Meta:
        unique_together=('question',)
        app_label = 'market'

    def __unicode__(self):
        return self.question

futures_market/market/models/order.py
from django.db import models
from market import Market
from stock import Stock
from trader import Trader
from datetime import datetime

class Order(models.Model):
    """Represents an order on the market."""
    market = models.ForeignKey(Market)
    stock = models.ForeignKey(Stock)
    trader = models.ForeignKey(Trader)
    
    ORDER_CHOICES = (
            ('B', 'BUY'),
            ('S', 'SELL'),
        )
    order = models.CharField(max_length=1, choices=ORDER_CHOICES)
    creation_time = models.DateTimeField(default=datetime.now())
    volume = models.IntegerField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    
    completed = models.BooleanField()
    completion_time = models.DateTimeField(blank=True, null=True)

    def __unicode__(self):
        output = [self.get_order_display(), unicode(self.volume), 'of', unicode(self.stock.name), 'at', unicode(self.price)]
        return ' '.join(output)

    class Meta:
        app_label = 'market'

futures_market/market/models/stock.py
from django.db import models
from market import Market

class Stock(models.Model):
    market = models.ForeignKey(Market)
    name = models.CharField(max_length=500)
    # max liquidation_price $999999.99. this may be larger than necessary
    liquidation_price = models.DecimalField(max_digits=8, decimal_places=2)
    stock_endowment = models.IntegerField() # initial stock endowment for users
    
    last_sale_price = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)
    last_sale_time = models.DateTimeField('last sale time', null=True, blank=True)

    class Meta:
        unique_together = ('market', 'name')
        app_label = 'market'

    def __unicode__(self):
        return self.name

futures_market/market/models/trader.py
from django.db import models
from market import Market

class Trader(models.Model):
    market = models.ForeignKey(Market)
    name = models.CharField(max_length=20) # no particular reason
    
    cash = models.DecimalField(max_digits=8, decimal_places=2)

    class Meta:
        unique_together = ('market', 'name')
        app_label = 'market'

    def __unicode__(self):
        return self.name

futures_market/market/forms.py
from django.forms import ModelForm, ChoiceField, Form, FileField, ModelChoiceField, HiddenInput, ValidationError
from market.models import *

class OrderForm(ModelForm):
    """Order form used in trader view."""
    # from http://stackoverflow.com/questions/1697702/how-to-pass-initial-parameter-to-djangos-modelform-instance/1697770#1697770
    # price from http://stackoverflow.com/questions/6473895/how-to-restrict-values-in-a-django-decimalfield

    # restricts prices to 0.0 through 2.0
    PRICE_CHOICES = [(i*.01, str(i*.01)) for i in range(1,201)]
    price = ChoiceField(choices=PRICE_CHOICES)
    trader = ModelChoiceField(label='', queryset=Trader.objects.all(), widget=HiddenInput())
    market = ModelChoiceField(label='', queryset=Market.objects.all(), widget=HiddenInput())

    def clean(self):
        """Validates the data. Ensures the trader has enough cash or shares
           to complete the requested order."""

        cleaned_data = self.cleaned_data
        if cleaned_data.get('order') and cleaned_data.get('stock') \
            and cleaned_data.get('volume') and cleaned_data.get('price'):
                t = cleaned_data['trader']
                if cleaned_data['order'] == 'B': # buy order
                    open_orders = Order.objects.filter(trader=t,
                            order='B', completed=False)
                    open_order_value = float(sum([o.volume * o.price for o in open_orders]))
                    open_order_value += int(cleaned_data['volume']) * float(cleaned_data['price'])

                    if open_order_value > t.cash:
                        raise ValidationError("You don't have enough cash!")

                elif cleaned_data['order'] == 'S': # sell order!
                    open_orders = sum(Order.objects.filter(trader=t, order='S',
                            stock=cleaned_data['stock'],
                            completed=False).values_list('volume', flat=True))
                    open_orders += cleaned_data['volume']

                    if open_orders > t.holding_set.get(stock=cleaned_data['stock']).shares:
                        raise ValidationError("You don't have enough shares!")
        return cleaned_data

    class Meta:
        model = Order
        fields = ('stock', 'order', 'volume', 'price', 'trader', 'market')

class UploadFileForm(Form):
    file = FileField()

futures_market/market/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.db import transaction
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime
from collections import defaultdict
from market.forms import *
from market.models import *
import json, calendar
import yaml
from django.contrib.admin.views.decorators import staff_member_required

def index(request):
    """Renders an index view listing all of the markets."""
    markets = Market.objects.all()
    form = UploadFileForm()
    return render_to_response('market/index.html', {'markets': markets, 'form': form}, context_instance=RequestContext(request))

@staff_member_required
def market(request, market_slug):
    """Renders and processes the market manager view, allowing opening
       and liquidating of markets and listing traders."""

    m = get_object_or_404(Market, slug=market_slug)
    if request.method == 'POST':
        if request.POST.get('open'):
            m.market_open = True
            m.save()
        elif request.POST.get('liquidate'):
            m.market_open = False
            m.save()
            liquidate(m)
        return HttpResponseRedirect(request.META['HTTP_REFERER'])

    else:
        return render_to_response('market/market.html', {'market': m}, context_instance=RequestContext(request))

@transaction.commit_manually
def liquidate(market):
    """Liquidates the market."""
    holdings = Holding.objects.filter(market=market)
    open_orders = Order.objects.filter(market=market,completed=False)
    for h in holdings:
        value = h.shares * h.stock.liquidation_price
        h.trader.cash += value
        h.trader.save()
    holdings.delete()
    open_orders.delete()
    transaction.commit()


def cancel_order(request):
    """Cancels orders."""
    if request.method == 'POST':
        trader = get_object_or_404(Trader, id=int(request.POST['trader']))
        order = get_object_or_404(Order, id=int(request.POST['order']))
        assert order.trader == trader

        if order.completed == False: # else bad news...
            order.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

@transaction.commit_manually
def resolve_order(order):
    """Resolves an order."""
    # find potential orders to resolve
    matches = Order.objects.filter(market=order.market,stock=order.stock)
    matches = matches.filter(completed=False).exclude(trader=order.trader)

    if order.order == 'B':
        matches = matches.filter(order='S')
        matches = matches.filter(price__lte=order.price)
        sorting = ['price']
    elif order.order == 'S':
        matches = matches.filter(order='B')
        matches = matches.filter(price__gte=order.price)
        sorting = ['-price']
    # matches are ordered by highest volume first and creation_time is used
    # to break ties, with older orders being completed first
    sorting += ['-volume', '-creation_time']
    matches = matches.order_by(*sorting)

    for match in matches:
        if order.completed: break

        if order.order == 'B':
            price = min(order.price, match.price)
            buyer = order.trader
            seller = match.trader
        elif order.order == 'S':
            price = max(order.price, match.price)
            buyer = match.trader
            seller = order.trader

        stock = order.stock
        buyer_holding = buyer.holding_set.get(stock=stock)
        seller_holding = seller.holding_set.get(stock=stock)
        volume = min(buyer.cash // price, order.volume, seller_holding.shares, match.volume)
        value = volume * price
        assert volume >= 0
        assert price >= 0

        # update data
        buyer.cash -= value
        seller.cash += value
        stock.last_sale_price = price
        stock.last_sale_time = datetime.now()
        buyer_holding.shares += volume
        seller_holding.shares -= volume

        # save data
        buyer.save()
        seller.save()
        stock.save()
        buyer_holding.save()
        seller_holding.save()

        # update orders
        for o in [order, match]:
            if volume == 0: break

            if o.volume != volume: # order will be split
                done = Order(market=o.market, stock=o.stock, trader=o.trader,
                      order=o.order, creation_time=o.creation_time, price=price,
                      volume=volume, completed=True, completion_time=datetime.now())
                done.save()
                o.volume -= volume
            else:
                o.completed = True
                o.price = price
                o.completion_time=datetime.now()
            o.save()

    transaction.commit()

def get_portfolio_data(market, trader):
    """Returns dictionary of data for a trader view given market and trader.
       Contains a trader, open and closed orders for that trader, and the
       order form."""
    open_orders = Order.objects.filter(market=market, trader=trader, completed=False)
    closed_orders = Order.objects.filter(market=market, trader=trader, completed=True)
    form = OrderForm()
    data = {'trader': trader, 'open_orders': open_orders, 'closed_orders': closed_orders, 'form': form} 

    return data

def update_portfolio(request, market_slug, trader_name):
    """Updates trader portfolio."""
    m = get_object_or_404(Market, slug=market_slug)
    t = get_object_or_404(Trader, name=trader_name, market=m)
    
    if t:
        data = get_portfolio_data(m, t)

        return render_to_response('market/portfolio.html', data, context_instance=RequestContext(request))

def trader(request, market_slug, trader_name):
    """Renders trader view and processes orders."""
    
    m = get_object_or_404(Market, slug=market_slug)
    t = get_object_or_404(Trader, name=trader_name, market=m)
    
    if request.method == 'POST': # Order being placed!
        form = OrderForm(request.POST)

        if form.is_valid():
            order = form.save(commit = False)
            order.market = m
            order.trader = t
            order.save()
            if m.market_open:
                resolve_order(order)

            return HttpResponseRedirect(request.path)
        else:
            data = get_portfolio_data(m, t)
            data['form'] = form
            return render_to_response('market/trader.html', data, context_instance=RequestContext(request))

    else: # normal GET request
        if t:
            data = get_portfolio_data(m, t)
            data['market'] = m
        d = {}
        d['prices'] = latest_prices(request, market_slug)
        d['orders'] = get_orders(request, market_slug)
        data['data'] = json.dumps(d)

        return render_to_response('market/trader.html', data, context_instance=RequestContext(request))

def latest_prices(request, market_slug):
    """Gets the latest stock prices and returns them as a list of JSON
       objects."""
    m = get_object_or_404(Market, slug=market_slug)
    stocks = Stock.objects.filter(market=m)
    data = []
    for stock in stocks:
        buy, sell = best_price(stock)
        if stock.last_sale_time:
            data.append({'last_sale_price': unicode(stock.last_sale_price),
                'last_sale_time': stock.last_sale_time.strftime('%d %b %y %H:%M:%S'),
                'best_buy': buy, 'best_sale': sell, 'name': stock.name})
        else:
            data.append({'last_sale_price': unicode(stock.last_sale_price),
                'last_sale_time': unicode(None),
                'best_buy': buy, 'best_sale': sell, 'name': stock.name})
    return data
    #return HttpResponse(json.dumps(data))

def best_price(stock):
    """Gets best BUY and best SELL order for stock."""
    buy = Order.objects.filter(stock=stock, order='B', completed=False).order_by('-price')
    if buy: buy = buy[0]
    else: buy = None

    sell = Order.objects.filter(stock=stock, order='S', completed=False).order_by('price')
    if sell: sell = sell[0]
    else: sell = None

    return unicode(buy), unicode(sell)

def get_orders(request, market_slug):
    """Returns JSON dictionary of orders on a market. Used to produce
       graphs."""

    m = get_object_or_404(Market, slug=market_slug)
    stocks = Stock.objects.filter(market=m)

    data = []
    for stock in stocks:
        s = {}
        s['label'] = stock.name
        o = Order.objects.filter(market=m, stock=stock, completed=True).values_list('completion_time', 'price').order_by('completion_time')
        orders = []
        for order in o:
            orders.append([js_timestamp_from_datetime(order[0]), float(order[1])])
        # current time and price
        #if orders:
            #orders.append([js_timestamp_from_datetime(datetime.now()), float(orders[-1][1])])

        # add stock to json data
        s['data'] = orders
        data.append(s)
    return data
    #return HttpResponse(json.dumps(data))

def update_market_info(request, market_slug):
    data = {}
    data['prices'] = latest_prices(request, market_slug)
    data['orders'] = get_orders(request, market_slug)
    data = json.dumps(data)

    return render_to_response('market/update-prices.html', {'data': data})

def js_timestamp_from_datetime(dt):
    return 1000 * calendar.timegm(dt.timetuple())

def validate_data(data):
    """Validates YAML data to make sure it contains all of the information
       necessary for creating a market."""

    # currently this function just uses lots of asserts and kind of sucks
    question = data.get('question')
    slug = data.get('slug')
    cash_endowment = data.get('cash_endowment')
    stocks_yaml = data.get('stocks')
    traders_yaml = data.get('traders')
    holdings_yaml = data.get('holdings', [])
    assert question != None and slug != None and cash_endowment != None and stocks_yaml != None and traders_yaml != None

    # validate traders
    for trader in traders_yaml:

futures_market/templates/market/index.html
{% extends "base.html" %}

{% block title %}Available Markets{% endblock %}

{% block content %}
<div class="grids">
    <div class="grid-8">
        <h2>Available Markets</h2>
        <ul>
            {% for m in markets %}
            <li>
            <a href="{% url market.views.market m.slug %}">{{ m.question }}</a>
            &mdash; <a href="{% url market.views.export_data m.slug %}">Export!</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="grid-8">
        <h2>Upload New Market</h2>
        <form enctype="multipart/form-data" method="POST" action="{% url market.views.upload_data %}" >
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Upload!" />
        </form>
    </div>
</div>
{% endblock %}

futures_market/templates/market/market.html
{% extends "base.html" %}

{% block title %}{{ market.question }}{% endblock %}


{% block content %}

<h1>{{ market.question }}</h1>

<h2>Stock Prices</h2>

<script type="text/javascript">
    function updateInfo() {
        $.ajax({
            url: '{% url market.views.update_market_info market.slug     %}',
            success: function(data) {
                $('#prices').html(data);
            },
            complete: function() {
                setTimeout(updateInfo, 1000);
            }
        });
    };
    updateInfo();
</script>

<div id="prices" class="grids">
    {% include "market/update-prices.html" %}
</div>

<hr />

<div class="grids">
    <div class="grid-8">
        <h2>Trader Portfolios</h2>

        <ul>
        {% for trader in market.trader_set.all %}
        <li><a href="{% url market.views.trader market.slug trader.name %}">{{ trader.name }}'s Portfolio</a></li>
        {% endfor %}
        </ul>
    </div>
</div>

<hr />

<div class="grids">
    <div class="grid-8">
    <h2>Market Manager</h2>

    <form method="POST" action="{% url market.views.market market.slug %}">
        {% csrf_token %}
        <input type="hidden" name="market" value="{{ market.id }}">
        {% if market.market_open %}
            <input type="submit" value="Close &amp; Liquidate" name="liquidate">
        {% else %}
            <input type="submit" value="Open" name="open">
        {% endif %}
    </form>
</div>
</div>

{% endblock %}

futures_market/templates/market/portfolio.html
<div class="grid-6" id="holdings">
    <h3>Holdings:</h3>
    <ul id="holdings">
        <li>Cash: {{ trader.cash }}</li>
        {% if trader.holding_set.all %}{% for holding in trader.holding_set.all %}
        <li>{{ holding.stock }}: {{ holding.shares }} shares</li>
        {% endfor %}{% endif %}
</div>

<div class="grid-5" id="open-orders">
    <h3>Open Orders:</h3>
    <ul id="open-orders">
        {% if open_orders %}{% for order in open_orders %}
            <li>{{ order }}
            <form action="{% url market.views.cancel_order %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="order" value="{{ order.id }}" />
                <input type="hidden" name="trader" value="{{ trader.id }}" />
                <input type="submit" value="Cancel" />
            </form></li>
        {% endfor %}
        {% else %}
            <li>No open orders.</li>
        {% endif %}
    </ul>
</div>
<div class="grid-5" id="closed-orders">
    <h3>Closed Orders:</h3>
    <ul id="closed-orders">
        {% if closed_orders %}{% for order in closed_orders %}
            <li>{{ order }}</li>
        {% endfor %}
        {% else %}
            <li>No closed orders.</li>
        {% endif %}
        </ul>
</div>

futures_market/templates/market/trader.html
{% extends "base.html" %}

{% block title %}{{ trader.name }}'s Portfolio on {{ trader.market.slug }}{% endblock %}

{% block content %}

<h1>{{ trader.name }} &ndash; {{ trader.market.question }}</h1>

<h2>Stock Prices</h2>

<script type="text/javascript">
    function updateInfo() {
        $.ajax({
            url: '{% url market.views.update_market_info trader.market.slug %}',
            success: function(data) {
                $('#prices').html(data);
            },
            complete: function() {
                setTimeout(updateInfo, 1000);
            }
        });
    };
    updateInfo();
</script>

<div id="prices" class="grids">
    {% include "market/update-prices.html" %}
</div>

<hr />

<h2>{{ trader.name }}'s Portfolio</h2>

<div id="portfolio" class="grids">
    {% include "market/portfolio.html" %}
</div>

<hr />

<h2>Available Actions</h2>

{% if trader.market.market_open %}
<p>The market is open! Let's act.</p>
<form method="POST" action="{% url market.views.trader trader.market.slug trader.name %}">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
        <strong>{{ error|escape }}</strong><br />
    {% endfor %}
    {% for field in form.visible_fields %}
        <p>{{ field.label_tag }} {{ field }}<br />
        {% for error in field.errors %}
            <strong>{{ error|escape }}</strong>
        {% endfor %}
        <input type="hidden" name="market" value="{{ trader.market.id }}" />
        <input type="hidden" name="trader" value="{{ trader.id }}" />
        </p>
    {% endfor %}
    <input type="submit" value="Place order!" />
</form>
{% else %}
<p>No actions available.</p>
{% endif %}


<script type="text/javascript">
    function updatePortfolio() {
        $.ajax({
            url: '{% url market.views.update_portfolio trader.market.slug trader.name %}',
            success: function(data) {
                $('#portfolio').html(data);
            },
            complete: function() {
                setTimeout(updateInfo, 1000);
            }
        });
    };
</script>

{% endblock %}

futures_market/templates/market/update-prices.html
{% autoescape off %}

<script type="text/javascript">
function updateGraph() {
    var options = {
        lines: { show: true },
        points: {show: true },
        xaxis: { mode: "time" } 
    };
    {% if data %}
    var stocks = {{ data }};
    var stocks = stocks.orders;
    {% else %}
    var stocks = [];
    {% endif %}
    var data = [];
    var placeholder = $("#placeholder");

        $.each(stocks, function(index, stock) {
            // add to current data

            if (stock.data.length > 0) {
                var last_price = stock.data[stock.data.length-1][1];
                d = new Date();
                utc = d.getTime();
                //localOffset = d.getTimezoneOffset() * 60000;
                //utc = localTime + localOffset;
                offset = -5;
                var now = utc + (3600000*offset);

                var current = new Array(now, last_price);
                stock.data.push(current);
                //console.log(now);
                //console.log(last_price);
                console.log(stock);
            }
            data.push(stock);

            // plot!
            $.plot(placeholder, data, options);
        });
};

function updatePrices() {
    // gets latest prices as JSON data
        var stocks = [];
        {% if data %}
        var data = {{ data }};
        var data = data.prices;
        {% else %}
        var data = [];
        {% endif %}

        // iterates over stocks and assembles them into nicely formatted lists
        $.each(data, function(index, stock) {
            stocks.push('<li id="' + stock.name + '">' + stock.name +
                "'s last price: " + stock.last_sale_price + ' at ' +
                stock.last_sale_time + ' (best buy offer: ' + stock.best_buy +
                '; best sell offer: ' + stock.best_sale + ')</li>');
        });

        // joins all the stock list into an unordered list and replaces the
        // previous one
        $('<ul/>', {
            'id': 'stock-list',
            html: stocks.join('')
        }).replaceAll('#stock-list');
};

updatePrices();
updateGraph();
</script>

<div class="grid-8" id="graph">
    <div id="placeholder" style="width:500px;height:300px;"></div>
</div>
<div class="grid-8" id="stock-prices">
    <p id="stock-list">Latest stock prices!</p>
</div>
{% endautoescape %}